### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Exolas** [FettLi/FUPS#4]
fn_mainHandler Zeile 339: In meinem Fall setzt diese Zeile die Funktion "FUPS_fnc_task_patrol_params" zusammen, diese ist jedoch nicht existent.

**Comment by FettLi** [comment]
Müsste eigentlich existent sein, war nur kein Code, sollte in der nächsten DEV Version gefixt sein.

**Comment by FettLi** [comment]
Da der Fehler nicht wieder aufgetreten ist: closed
